import { handlePostRegister, handlePostLogin } from "../src/server/HandlerAuth";
import { handleGetStudentProgress } from "../src/server/HandlerReporting";
import { HandlerPostEntryStep, type HandlerDeps } from "../src/server/HandlerPostEntryStep";
import { InMemoryInvariantRegistry } from "../src/invariants/invariants.registry";
import { createDefaultStudentPolicy } from "../src/stepmaster/stepmaster.policy";
import { loadAllCoursesFromDir } from "../src/invariants/invariants.course-loader";
import path from "path";
import assert from "assert";
import { IncomingMessage, ServerResponse } from "http";
import { Socket } from "net";

// Mock Request/Response helpers
function createMockReq(url: string, headers: Record<string, string> = {}): IncomingMessage {
    const socket = new Socket();
    const req = new IncomingMessage(socket);
    req.url = url;
    req.headers = headers;
    // Mock host header for URL parsing
    if (!req.headers.host) {
        req.headers.host = "localhost";
    }
    return req;
}

function createMockRes(): ServerResponse & { _getData: () => string, _getStatusCode: () => number } {
    const req = new IncomingMessage(new Socket());
    const res = new ServerResponse(req) as any;
    let data = "";
    let statusCode = 200;

    res.writeHead = (code: number, headers?: any) => {
        statusCode = code;
        return res;
    };

    res.end = (chunk: any) => {
        if (chunk) data += chunk;
        res.emit("finish");
    };

    res._getData = () => data;
    res._getStatusCode = () => statusCode;

    return res;
}

async function runTest() {
    console.log("Starting verify-reporting test...");

    // 1. Setup Deps
    const coursesDir = path.join(process.cwd(), "config/courses");
    const registry = loadAllCoursesFromDir({ path: coursesDir });

    const deps: HandlerDeps = {
        invariantRegistry: registry,
        policy: createDefaultStudentPolicy(),
        log: (msg) => console.log(msg),
    };

    // 2. Register Users
    console.log("\n--- Registering Users ---");
    const teacherReg = await handlePostRegister({ username: "teacher_rep", password: "pwd", role: "teacher" });
    const studentReg = await handlePostRegister({ username: "student_rep", password: "pwd", role: "student" });

    const teacherToken = teacherReg.token!;
    const studentToken = studentReg.token!;
    const studentUserId = studentReg.userId!; // We need the ID generated by the service

    console.log(`Teacher Token: ${teacherToken}`);
    console.log(`Student Token: ${studentToken}`);
    console.log(`Student ID: ${studentUserId}`);

    // 3. Create Session Data for Student
    console.log("\n--- Creating Student Session ---");
    const stepReq = {
        sessionId: "sess_rep_1",
        courseId: "default",
        expressionLatex: "1/2 + 1/3",
        selectionPath: null,
        token: studentToken
    };
    // This will implicitly create a session linked to the student
    await HandlerPostEntryStep(stepReq, deps);

    // 4. Verify Teacher Access (Success)
    console.log("\n--- Testing Teacher Access ---");
    const req1 = createMockReq(`/api/teacher/student-progress?userId=${studentUserId}`, {
        authorization: `Bearer ${teacherToken}`
    });
    const res1 = createMockRes();

    await handleGetStudentProgress(req1, res1);

    console.log(`Status: ${res1._getStatusCode()}`);
    console.log(`Body: ${res1._getData()}`);

    assert.strictEqual(res1._getStatusCode(), 200);
    const body1 = JSON.parse(res1._getData());
    assert.strictEqual(body1.studentId, studentUserId);
    assert.strictEqual(body1.totalSessions, 1);
    assert.strictEqual(body1.sessions[0].sessionId, "sess_rep_1");
    console.log("PASS: Teacher retrieved student progress.");

    // 5. Verify Student Access (Forbidden)
    console.log("\n--- Testing Student Access (Forbidden) ---");
    const req2 = createMockReq(`/api/teacher/student-progress?userId=${studentUserId}`, {
        authorization: `Bearer ${studentToken}`
    });
    const res2 = createMockRes();

    await handleGetStudentProgress(req2, res2);

    console.log(`Status: ${res2._getStatusCode()}`);
    console.log(`Body: ${res2._getData()}`);

    assert.strictEqual(res2._getStatusCode(), 403);
    console.log("PASS: Student was forbidden.");

    // 6. Verify Unauthorized Access (No Token)
    console.log("\n--- Testing Unauthorized Access ---");
    const req3 = createMockReq(`/api/teacher/student-progress?userId=${studentUserId}`);
    const res3 = createMockRes();

    await handleGetStudentProgress(req3, res3);

    console.log(`Status: ${res3._getStatusCode()}`);
    assert.strictEqual(res3._getStatusCode(), 401);
    console.log("PASS: Unauthorized request rejected.");

    console.log("\nAll Reporting tests passed!");
}

runTest().catch(err => {
    console.error("Test failed:", err);
    process.exit(1);
});
